language: python
python: 3.6
services:
- mongodb
install: pip install -r requirements.txt
script:
- "./test.sh"
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: AKIAVDEUFRXDCKCIBCWP
    secret_access_key:
      secure: IUxz3P6RrY3MMTUikr3VKxxdVuv8tAwPQqsvFIaT9rn460VoydiDZzj8xkSrYjyHvLiWIeJP163ZuhGcROXCf2y9VLVs/XMHc77HYjUGu4yY4W6DBKsmSDXrUmuabA06yL4/yuFdChLVAZ6HtyO6cpVNivuEa7bHmT3A1C/9l64tj70+JiHFSveOoX5iaeJb63vHM459Rh7NOE3Iqe6+8p96HpB3/jtfTjuj9QU0ndWKqqn/qDelN+HGigSGQNInoDOQkMHccEjSgaKc4fXkqhSvpGM/6SdJrwFe0qMXkyfc7wr2pxWcIeJieJfgI07HwfIEvuWvxPBev0PvK05mQC+zR0d8MQCsVYGnavgvAvlsZyrP3JxdrSZlytmHrxvBiiIdbCcrnFeuEj7o0sK08sworedwvZ+EownG6jZnxnMgaEbOcewerDpgVzSTcmSsAs6YZftHgFE+gbET8iU3yJduR4My17rXF27ZDn6szejn2Lfup8S/GsiQVwl6y3oHwz9yfgBY7+5BkJhQYcJv+CLeX0KjsmI+5hNWlHplfAu+++kEbag/R9dsXLpsCcEAbP+20/MwWV/U/hwbdbGP0xPQzN/DwN9zMBtrdTU+ZnzBSAvoSLDdtgUmzV6GuyTsSsbsKm/hwNl8PgOWK82amUNRPRVgxyrSikV6t+WULXE=
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &1
      repo: andrewpsuedonym/goldenShoe
    bucket: small-golden-shoe-demo
    region: eu-west-2
  - provider: codedeploy
    access_key_id: AKIAVDEUFRXDCKCIBCWP
    secret_access_key:
      secure: IUxz3P6RrY3MMTUikr3VKxxdVuv8tAwPQqsvFIaT9rn460VoydiDZzj8xkSrYjyHvLiWIeJP163ZuhGcROXCf2y9VLVs/XMHc77HYjUGu4yY4W6DBKsmSDXrUmuabA06yL4/yuFdChLVAZ6HtyO6cpVNivuEa7bHmT3A1C/9l64tj70+JiHFSveOoX5iaeJb63vHM459Rh7NOE3Iqe6+8p96HpB3/jtfTjuj9QU0ndWKqqn/qDelN+HGigSGQNInoDOQkMHccEjSgaKc4fXkqhSvpGM/6SdJrwFe0qMXkyfc7wr2pxWcIeJieJfgI07HwfIEvuWvxPBev0PvK05mQC+zR0d8MQCsVYGnavgvAvlsZyrP3JxdrSZlytmHrxvBiiIdbCcrnFeuEj7o0sK08sworedwvZ+EownG6jZnxnMgaEbOcewerDpgVzSTcmSsAs6YZftHgFE+gbET8iU3yJduR4My17rXF27ZDn6szejn2Lfup8S/GsiQVwl6y3oHwz9yfgBY7+5BkJhQYcJv+CLeX0KjsmI+5hNWlHplfAu+++kEbag/R9dsXLpsCcEAbP+20/MwWV/U/hwbdbGP0xPQzN/DwN9zMBtrdTU+ZnzBSAvoSLDdtgUmzV6GuyTsSsbsKm/hwNl8PgOWK82amUNRPRVgxyrSikV6t+WULXE=
    bucket: small-golden-shoe-demo
    key: latest.zip
    bundle_type: zip
    application: GoldenShoe
    deployment_group: GoldenShoe
    region: eu-west-2
    on: *1
    wait_until_deployed: true
