version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ec2-user/shoe

hooks:
    BeforeInstall:
      - location: ./home/ec2-user/shoe/install.sh
    ApplicationStart:
      - location: ./home/ec2-user/shoe/run.sh
